f = open("textFile.txt", "w")
f.write("I Love Mathematics.")
f.write("\nMathematics is my favorite subject")
print("Data is written successfully!!")
f.close()
f = open("textFile.txt", "r")
call = f.read(12)
print(call)
f.close()
